### ISSUE TITLE
Custom joins

### ISSUE THREAD

**Issue by mattlaw** [FCO/Red#345] opened 2019-09-05 08:44 UTC
One itch I always found myself wanting to scratch with `DBIx::Class` is creating queries with joins that weren't necessarily declared in the schema as relationships, e.g. EAV-style joins:

```sql
SELECT entity e
  JOIN attributes a
    ON a.entity = e.id AND a.attribute = ? AND a.value = ?
```

**Comment by FCO** [comment] 2019-09-05 08:55
Maybe something like this could make sense:

```perl6
Model1.^all.flatmap: -> $m1 { Model2.^all.grep: { $m1.col == .related-col } }
```

**Comment by mattlaw** [comment] 2019-09-05 09:02
If that can be made to work and results in a join condition, that would be great!

**Comment by FCO** [comment] 2019-09-05 09:05
Great! I'm thinking of any `map/flatmap` that returns a `ResultSeq` to become a `join`... and use the `ResultSeq`'s filter as the `on` condition...

**Comment by Xliff** [comment] 2019-09-07 13:37
Would it be possible to add a .join method to Red::ResultSeq so that it's easier for new users to grasp?

**Comment by FCO** [comment] 2019-09-07 14:15
I like the idea of ResultSeq mimicking Seq...

**Comment by Xliff** [comment] 2019-09-07 14:29
Would something like this work?

```
method join(&filter where *.signature.returns =:= Red::ResultSeq) { ... }
```
The only problem is that &filter would explicitly have to specify a signature, which might not be what you want.

**Comment by FCO** [comment] 2019-09-07 14:33
Maybe:

```perl6
method join(&filter where *.(self) ~~ Red::ResultSeq) { ... }
```

**Comment by Xliff** [comment] 2019-09-07 14:38
Would that be:

```
method join(&filter where *.WHAT ~~ Red::ResultSeq) { ... }
```

**Comment by FCO** [comment] 2019-09-07 14:43
No:

```
fernando@MBP-de-Fernando Red % perl6 -e 'my &filter = { 42 }; sub a(&f where *.WHAT ~~ Int) { say f }; a &filter'
Constraint type check failed in binding to parameter '&f'; expected anonymous constraint to be met but got -> ;; $_? is raw { #`...
  in sub a at -e line 1
  in block <unit> at -e line 1

fernando@MBP-de-Fernando Red % perl6 -e 'my &filter = { 42 }; sub a(&f where .() ~~ Int) { say f }; a &filter'   
42
```

**Comment by Xliff** [comment] 2019-09-07 14:44
Oh, so you actually are running the filter in the where clause and checking the result...

Huh!

**Comment by FCO** [comment] 2019-09-07 14:46
Every block passed to **Red** (on `map`, `grep` or whatever) are run multiple times, because we should discover what's inside of it... So running it on the signature isn't a real problem... :)

**Comment by Xliff** [comment] 2019-10-30 00:31
Given the following example:

```
use Red;
my $*RED-DB = database "SQLite";

model Bla { ... }
model Ble { ... }
model Bli { ... }

model Bla {
   has UInt $.id     is serial;
   has UInt $!ble-id is referencing( *.id, :model<Ble>);
   has      $.ble    is relationship( *.ble-id, :model<Ble> );
}

model Ble {
   has UInt $.id     is serial;
   has UInt $!bli-id is referencing( *.id, :model<Bli>, :optional );
   has      $.bli    is relationship( *.bli-id, :model<Bli> );
}

model Bli {
   has UInt $.id    is serial;
   has Int  $.value is column;
}

Bla.^create-table; Ble.^create-table; Bli.^create-table;
my $*RED-DEBUG = True;

say Bla.^all.grep: { .ble.bli.value == 42 }
```

The SQL emitted should be a left join:

```
SQL : SELECT
   bla.id , bla.ble_id as "ble-id"
FROM
   bla
    JOIN ble as bla_ble ON bla.ble_id = bla_ble.id	
    LEFT JOIN bli as bla_ble_bli ON bla_ble.bli_id = bla_ble_bli.id	
WHERE
   bla_ble_bli.value = 42
BIND: []
()
```

**Comment by FCO** [comment] 2019-11-01 08:22
I've been wondering... maybe the `:optional` should be on the relationship instead of on the (fk) column... that way I could use the same fk on 2 different relationships, one with LEFT JOIN and the other with regular JOIN...

**Comment by Xliff** [comment] 2019-11-01 08:44
@FCO - Well the reason I put it on the FK is so that Red can check that column for creation and NOT put a "NOT NULL" marker on it. Since it is an optional key, it should be able to take a null.

If you can do that on the relationship and still easily get the information, then that makes this issue moot. :)

**Comment by FCO** [comment] 2019-11-03 22:03
@mattlaw I was able to create a custom join using the bases used by relationship. I'me thinking in a way of creating a new syntax using it:

```
perl6 -I. -MRed -e '
my $*RED-DB = database "SQLite";

model Bla { has $!id is serial; has Int $.ble is column }
model Ble { has $!id is serial; has Int $.bla is column }

Bla.^create-table; Ble.^create-table;
my $*RED-DEBUG = True;

.say for Bla.^all.grep: -> $bla { Ble.^alias("test", :base($bla), :relationship{.id == $bla.ble}).bla == 42 }

'
SQL : SELECT
   bla.id , bla.ble 
FROM
   bla
    JOIN ble as test ON test.id = bla.ble	
WHERE
   test.bla = 42
BIND: []
```

**Comment by FCO** [comment] 2019-11-03 22:11
not sure yet if in the right direction, but:

```
perl6 -I. -MRed -e '
my $*RED-DB = database "SQLite";

model Bla { has $!id is serial; has Int $.ble is column }
model Ble { has $!id is serial; has Int $.bla is column }

Bla.^create-table; Ble.^create-table;
my $*RED-DEBUG = True;

.say for Bla.^all.grep: { .^join(Ble, *.ble == *.id).bla == 42 }

'
SQL : SELECT
   bla.id , bla.ble 
FROM
   bla
    JOIN ble as ble_1 ON bla.ble = ble_1.id	
WHERE
   ble_1.bla = 42
BIND: []
```

**Comment by FCO** [comment] 2019-11-04 00:59
https://github.com/FCO/Red/blob/join/t/33-join.t

**Comment by FCO** [comment] 2019-11-04 07:35
https://github.com/FCO/Red/blob/join/t/33-join.t#L18
Fix this example to use `.^join`

**Comment by FCO** [comment] 2019-11-04 07:42
```perl6
.say for Bla.^join(Ble, *.ble == *.bla).^all.map: *.bla
```

**Comment by FCO** [comment] 2019-11-04 08:21
```
perl6 -I. -MRed -e '
my $*RED-DB = database "SQLite";

model Bla { has $!id is serial; has Int $.ble is column }
model Ble { has $!id is serial; has Int $.bla is column }

Bla.^create-table; Ble.^create-table; Bla.^create: :ble($_) for ^10; Ble.^create: :bla($_) for ^10;
my $*RED-DEBUG = True;

.say for Bla.^join(Ble, *.ble / 2 == *.bla).^all.grep({ Bla.id % 2 == 0 }).map: { .bla }

'
SQL : SELECT
   ble_1.bla as "data_1"
FROM
   bla
    JOIN ble as ble_1 ON bla.ble / 2 = ble_1.bla	
WHERE
   bla.id % 2 = 0
BIND: []
0
1
2
3
4
```

**Comment by FCO** [comment] 2019-11-04 08:42
I still need to create the `ResultSeq.join`, that will probably be something like:
```perl6
method join(Red::Model \model, &on) {
   self.of.^join(model, &on).clone: :filter($!filter), ...
}

**Comment by FCO** [comment] 2019-11-04 12:58
```
perl6 -I. -MRed -e '                      

model Bla { has $!id is serial; has Int $.ble is column }
model Ble { has $!id is serial; has Int $.bla is column }
my $*RED-DB = database "SQLite";
Bla.^create-table;
Ble.^create-table;

my $*RED-DEBUG = True;

.say for Bla.^all.grep(*.ble % 2 == 0).join(Ble, *.ble / 2 == *.bla).map(*.bla)

'
SQL : SELECT
   ble_1.bla as "data_1"
FROM
   bla
    JOIN ble as ble_1 ON bla.ble / 2 = ble_1.bla	
WHERE
   bla.ble % 2 = 0
BIND: []
```

**Comment by FCO** [comment] 2019-11-04 22:26
@Xliff, @mattlaw:

```
perl6 -I. -MRed -e '


my $*RED-DB = database "SQLite";

model Bla { ... }
model Ble { ... }
model Bli { ... }

model Bla {
   has UInt $.id     is serial;
   has UInt $!ble-id is referencing( *.id, :model<Ble>);
   has      $.ble    is relationship( *.ble-id, :model<Ble> );            
}

model Ble {
   has UInt $.id     is serial;
   has UInt $!bli-id is referencing( *.id, :model<Bli>, :!nullable );           
   has      $.bli    is relationship( *.bli-id, :model<Bli> );           
}

model Bli {
   has UInt $.id    is serial;
   has Int  $.value is column;
}

Bla.^create-table; Ble.^create-table; Bli.^create-table;
my $*RED-DEBUG = True;

say Bla.^all.grep: { .ble.bli.value == 42 }

'
SQL : SELECT
   bla.id , bla.ble_id as "ble-id"
FROM
   bla
    LEFT JOIN ble as bla_ble ON bla.ble_id = bla_ble.id	
    INNER JOIN bli as bla_ble_bli ON bla_ble.bli_id = bla_ble_bli.id	
WHERE
   bla_ble_bli.value = 42
BIND: []
()
```

**Comment by FCO** [comment] 2019-11-04 22:27
@mattlaw:

```
perl6 -I. -MRed -e '

model Bla { has $!id is serial; has Int $.ble is column }
model Ble { has $!id is serial; has Int $.bla is column }
my $*RED-DB = database "SQLite";
Bla.^create-table;
Ble.^create-table;
Bla.^create: :ble($_) for ^20; Ble.^create(:1bla) xx 10;
my $*RED-DEBUG = True;

.say for Bla.^all.join(:left, Ble, *.ble / 2 == *.bla).map(*.bla)    

'
SQL : SELECT
   ble_1.bla as "data_1"
FROM
   bla
    LEFT JOIN ble as ble_1 ON bla.ble / 2 = ble_1.bla	
BIND: []
(Int)
(Int)
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
```

**Comment by mattlaw** [comment] 2019-11-05 09:53
Looks great!

One question though: why no placeholders for the values in the join conditions?

**Comment by FCO** [comment] 2019-11-05 12:31
It is/was not implemented on every op yet, but the idea is that hardcoded values do not need to be binded, but everything inside a container (so, maybe something the user could have changed) should be bonded, so, the last example is right, but this next example should bind:

```
perl6 -I. -MRed -e '

model Bla { has $!id is serial; has Int $.ble is column }
model Ble { has $!id is serial; has Int $.bla is column }
my $*RED-DB = database "SQLite";
Bla.^create-table;
Ble.^create-table;
Bla.^create: :ble($_) for ^20; Ble.^create(:1bla) xx 10;
my $*RED-DEBUG = True;                           

.say for Bla.^all.join(:left, Ble, *.ble / ($ = 2) == *.bla).map(*.bla)

'
SQL : SELECT
   ble_1.bla as "data_1"
FROM
   bla
    LEFT JOIN ble as ble_1 ON bla.ble / ? = ble_1.bla
BIND: [2]
(Int)
(Int)
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
(Int)
```

**Comment by Altai-man** [comment] 2019-11-16 19:42
Is the last example working already? For me it gives this error:

```
Cannot resolve caller ACCEPTS(Bool:U: Mu:U); none of these signatures match:
    (Bool:D: Mu \topic, *%_)
    (Bool:U: \topic, *%_)
  in method default-type-for at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/44F94C2129701F4D3DAE62F858370813D3CDD155 (Red::Driver::SQLite) line 1
  in method translate at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/7162B4F35C42B832501B0AD9A79B120B44CE818D (Red::Driver::CommonSQL) line 528
  in method translate at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/7162B4F35C42B832501B0AD9A79B120B44CE818D (Red::Driver::CommonSQL) line 518
  in block  at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/7162B4F35C42B832501B0AD9A79B120B44CE818D (Red::Driver::CommonSQL) line 554
  in method translate at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/7162B4F35C42B832501B0AD9A79B120B44CE818D (Red::Driver::CommonSQL) line 550
  in method prepare at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/97F0F6FA412E8F7FA0930CEE84B9AB8E045E5A6C (Red::Driver) line 46
  in method execute at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/97F0F6FA412E8F7FA0930CEE84B9AB8E045E5A6C (Red::Driver) line 76
  in method create-table at /home/koto/.rakudobrew/versions/moar-2019.07/install/share/perl6/site/sources/0A3152D387D23EDEB6D5DEA3B6D22EC77A7B7B1E (MetamodelX::Red::Model) line 277
  in block <unit> at perl6.p6 line 31
```

It fails at `Bla.^create-table;` line.

**Comment by FCO** [comment] 2019-11-16 23:56
Are you using the `join` branch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Altai-man** [comment] 2019-11-17 09:17
Oh, I am not. I need a simple join (e.g. `SELECT * FROM posts JOIN persons ON posts.author_id = persons.id;`) and don't want to do `is relationship`. It is impossible right now, right?

**Comment by FCO** [comment] 2019-11-17 11:03
Only on join branch... sorry... :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment] 2019-11-17 11:13
But it should be possible to do:

```sql
SELECT
    *
FROM
    posts,
    persons
WHERE
    posts.person_id = persons.id
```

When I get my computer I’ll test if it really works...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment] 2019-11-17 11:13
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment] 2019-11-17 16:43
It’s not working... :( maybe it would be better to use the join branch...

**Comment by Altai-man** [comment] 2019-11-17 20:55
@FCO can we expect the branch being merged anytime soon?
I'd like to use Red for my advent post, and saying "This is a work in progress, but you can use a branch" would be a bit LTA.

**Comment by FCO** [comment] 2019-11-17 21:09
I am planing to merge it (with the :api<2>) before my advent post...

**Comment by Altai-man** [comment] 2019-11-17 21:11
Great! Thanks, I'll use `join` branch for now, will try to write a query with the code above...

**Comment by Altai-man** [comment] 2019-11-19 21:49
https://gist.github.com/Altai-man/cdc026a2dd6532eeebe1ce4b80148376 <- an odd error on latest join branch.

**Comment by FCO** [comment] 2019-11-19 21:58
Yes, that’s odd... I’ll take a look at it as soon as possible... until it’s fixed, running a map to return only the columns you are going to use must work...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Altai-man** [comment] 2019-11-19 22:02
The issue is that I am having issues with *.map too... https://gist.github.com/Altai-man/df72e797f0b9712bb788a7f3ebb47676

And what is odd is that in both cases (with map and without) it says that the column not found is different every time.

**Comment by FCO** [comment] 2019-11-19 22:07
I’m not with my computer now, but I think you should be using a User column over there... * will be a User object... you probably could use { Post.body } as a work around...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Altai-man** [comment] 2019-11-19 22:21
Not sure if any useful, but looked at it a bit:
https://github.com/FCO/Red/blob/master/lib/Red/ResultSeq/Iterator.pm6#L33
^ here $!of is `User_1` type (created using MOP?) and it's `^columns` evaluates to an empty array. An initialization of them is missing somewhere, I think.

**Comment by FCO** [comment] 2019-11-19 23:04
@Altai-man on `.^create` there is a type... `:author_id(1)` should be `:author-id(1)`...

**Comment by FCO** [comment] 2019-11-19 23:35
@Altai-man 

```
perl6 -I. -e '


use Red;

model User is rw is table<persons> {
    has Int $.id is serial;
    has Str $.username is column{ :unique, :!nullable };
    has Str $.password is column{ :!nullable };
}

model Post is rw {
    has Int $.id is serial;
    has Int $!author-id is referencing{ User.id };
    has DateTime $.created is column{ :!nullable } .= now;
    has Str $.title is column{ :!nullable };
    has Str $.body is column{ :!nullable };
}

$GLOBAL::RED-DB = database "SQLite";

my $*RED-DEBUG = True;

User.^create-table: :if-not-exists;
Post.^create-table: :if-not-exists;

User.^create: :username("John"), :password("John");
Post.^create(:author-id(1), title => "Heh", body => "MY BODY");

say Post.^all.join(:left, User, *.author-id == *.id).map({ .username, Post.title });

'
SQL : CREATE TABLE persons(
   id integer NOT NULL primary key AUTOINCREMENT,
   username varchar(255) NOT NULL ,
   password varchar(255) NOT NULL ,
   UNIQUE (username)
)
BIND: []
SQL : CREATE TABLE post(
   id integer NOT NULL primary key AUTOINCREMENT,
   author_id integer NULL references persons(id),
   created varchar(255) NOT NULL ,
   title varchar(255) NOT NULL ,
   body varchar(255) NOT NULL 
)
BIND: []
SQL : INSERT INTO persons(
   username,
   password
)
VALUES(
   ?,
   ?
)
BIND: ["John", "John"]
SQL : SELECT
   persons.id , persons.username , persons.password 
FROM
   persons
WHERE
   _rowid_ = last_insert_rowid()
LIMIT 1
BIND: []
SQL : INSERT INTO post(
   created,
   body,
   title,
   author_id
)
VALUES(
   ?,
   ?,
   ?,
   ?
)
BIND: ["2019-11-19T23:35:05.812944Z", "MY BODY", "Heh", 1]
SQL : SELECT
   post.id , post.author_id as "author-id", post.created , post.title , post.body 
FROM
   post
WHERE
   _rowid_ = last_insert_rowid()
LIMIT 1
BIND: []
SQL : SELECT
   user_1.username as "data_1", post.title as "data_2"
FROM
   post
    LEFT JOIN persons as user_1 ON post.author_id = user_1.id
BIND: []
((John Heh))
```

**Comment by FCO** [comment] 2020-01-08 03:18
This is on master now... should it be closed?

**Comment by Altai-man** [comment] 2020-01-08 09:23
Can one e.g. re-write https://github.com/Altai-man/sample-cro-crud/blob/master/lib/Blog/Database.pm6#L34-L37 in Red?
If yes, then I'd consider custom joins to work.

**Comment by FCO** [comment] 2020-01-08 10:42
If I got it right, it’s what I want with https://github.com/FCO/Red/issues/416 (almost there…) and not with custom joins… Did I get it?

**Comment by Altai-man** [comment] 2020-01-08 17:07
I am not sure, the task is, let me see...
Let's way we have two models, User and Post. Each post has $.author-id containing ID of corresponding User instance. The query is "join users and posts on author-id and select all data for all posts, but instead of author ID I want to see author's $.firstname value to display that in a single query".

**Comment by FCO** [comment] 2020-01-08 19:24
Yes... that’s what I’m planing for that issue... you’ll be able to do a `Post.^all` and that will prefetch the author data, so, `$post.author.name` will not run another query...

I know that’s not what you want, but if you want, for example, only the post’s title and the author’s name, you could do something like:

```perl6
.say forPost.^all.map: { “post ‘{ .title }’ by { .author.name }” }
```

And that should work...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Altai-man** [comment] 2020-01-08 20:48
If it is related to other ticket, then close this one according to your own opinion. :+1:

**Comment by Xliff** [comment] 2020-01-09 03:40
@FCO: I do like the prefetch aspect _in that situation_, but if I did something like this:

```perl6
.say forPost.^all.map: { "Post '{ .title }' };
```

Would there still be a prefetch for .author?

**Comment by FCO** [comment] 2020-01-09 07:17
The

```perl6
.say for Post.^all.map: { “post ‘{ .title }’ by { .author.name }” }
```

Do not use the prefetch feature and already work now. It just uses a join with the `Person` table because the `author` relationship was used. If that relationship wasn’t used, there would be no join.

The prefetch feature idea is that it will only automatically add a join with the `$` relationships when you are returning the whole object, for example:

```perl6
.say for Post.^all
```

Would do join with the `Person` table and each object returned would have the `.author` pre-populated.

Does that make sense?

**Comment by FCO** [comment] 2020-01-09 12:23
@Xliff 
```
$ raku -I. -Iexamples/blog2 -MRed -MPost -MPerson -e '
red-defaults default => database "SQLite";
Post.^create-table; Person.^create-table;
my $*RED-DEBUG = True;
.say for Post.^all.map: { “post ‘{ .title }’ by { .author.name }” }
'
SQL : SELECT
   'post ‘' || post.title || '’ by ' || post_author.name as "data_1"
FROM
   post
    LEFT JOIN person as post_author ON post.author_id = post_author.id
BIND: []
$ raku -I. -Iexamples/blog2 -MRed -MPost -MPerson -e '
red-defaults default => database "SQLite";
Post.^create-table; Person.^create-table;
my $*RED-DEBUG = True;
.say for Post.^all.map: { “post ‘{ .title }’” }
'
SQL : SELECT
   'post ‘' || post.title || '’' as "data_1"
FROM
   post
BIND: []
```

**Comment by Xliff** [comment] 2020-01-09 12:59
@FCO: Nice! How are you detecting for the presence of other models in .map?

**Comment by FCO** [comment] 2020-01-09 13:15
@Xliff we just include the “tables” (table aliases as well) that are returned by the map’s block...

**Comment by FCO** [comment] 2020-01-09 13:20
@Xliff That’s why you can also have join of join like this:

```
fernando@MBP-de-Fernando Red % perl6 -I. -MRed -e '
my $*RED-DB = database "SQLite";

model Bla { ... }
model Ble { ... }
model Bli { ... }
model Bla {
   has UInt $.id     is serial;
   has UInt $!ble-id is referencing( *.id, :model<Ble>);
   has      $.ble    is relationship( *.ble-id, :model<Ble> );
}

model Ble {
   has UInt $.id     is serial;
   has UInt $!bli-id is referencing( *.id, :model<Bli> );
   has      $.bli    is relationship( *.bli-id, :model<Bli> );
}

model Bli {
   has UInt $.id    is serial;
   has Int  $.value is column;
}



Bla.^create-table; Ble.^create-table; Bli.^create-table;
my $*RED-DEBUG = True;

say Bla.^all.grep: { .ble.bli.value == 42 }

'
SQL : SELECT
   bla.id , bla.ble_id as "ble-id"
FROM
   bla
    JOIN ble as bla_ble ON bla.ble_id = bla_ble.id 
    JOIN bli as bla_ble_bli ON bla_ble.bli_id = bla_ble_bli.id 
WHERE
   bla_ble_bli.value = 42
BIND: []
()
```

**Comment by FCO** [comment] 2020-06-26 23:04
@Altai-man just to let you know that https://github.com/FCO/Red/issues/416 is already working (for some time, sorry the delay)

**Closed** 2020-06-26 23:06 UTC

**Comment by FCO** [comment] 2020-06-28 13:37
@mattlaw I'm going to rename `ResultSeq.join` to `ResultSeq.join-model` because I need `ResultSeq.join` to mimic `Positional.join`, like:

```raku
Post.^all.map(*.name).join: ", "
```
